<?php


/**
 * @file
 * Contains insider_post.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function insider_suggestion_form_handler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the insider_post module.
    case 'help.page.insider_suggestion_form_handler':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manages certain webforms if we want them to be posted anonymously.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_alter().
 */
function insider_suggestion_form_handler_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  $formObject = $form_state->getFormObject();
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $entity = $formObject->getEntity();
    if($entity->getEntityTypeId() == "webform_submission") {
      $form['#attached']['library'][] = 'insider_suggestion_form_handler/insider.text.format.fix';
    }
  }
}
